### ISSUE TITLE
Add ability to hide specific dashboards

### ISSUE THREAD

**Issue by aleisalem** [turbot/powerpipe#485]
**Is your feature request related to a problem? Please describe.**
There is currently no way (I know of) to hide some of the dashboards displayed on the web interface. I want to be able to focus on (a) the AWS services we are using, and (b) just a couple of insights that the "Dashboard" and "Detail" dashboards of each service would give us.

**Describe the solution you'd like**
- Either via the `powerpipe` command or in some config file (say `mod.pp`), it would be great to specify the dashboards to show or hide (preferable explicit hiding).
- From the GUI would also be OK, maybe via profiles (i.e., profile "default" shows all dashboards, while profile "only_s3" shows only S3-related dashboards).

**Describe alternatives you've considered**
- I tried a quick-and-dirty hack of removing the directories of some of the dashboards I am not interested in seeing, but that broke the process when running `powerpipe server`, because some dashboards depend on others. Decoupling them might prove to be either cumbersome, not possible, or both.
- I also tried looking into hiding dashboards via the `powerpipe dashboard show` commands, but it does not seem to be allowing this capability.

**Additional context**
Apologies if this feature somehow exists but I could not really find that anywhere.

Cheers,
Alei

**Comment by ekkohdev** [comment]
I was looking for the same functionality for a similar use case. It would be great to get this reopened.

We have specific benchmark requirements as part of certification and compliance assessments that use a subset of controls from frameworks like CIS. We have custom benchmarks defined in a custom mod that run the particular subset of controls. I'd like to have only our custom benchmarks visible in the UI when running `powerpipe server`, instead of all of the items from the mod dependencies as well.

It adds a lot of noise and causes user confusion when we are wanting to provide a "tailored" experience.
